version: 0.0
os: linux
hooks:
  ApplicationStop:
    - location: Scripts/elb/deregister_from_elb.sh
    - location: Scripts/elb/stop_httpd.sh
      runas: root
  AfterInstall:
    - location: Scripts/compile.sh
      timeout: 60
      runas: root
  ApplicationStart:
    - location: Scripts/start.sh
      timeout: 180
      runas: root
    - location: Scripts/elb/start_httpd.sh
      runas: root
    - location: Scripts/register_with_elb.sh
  ValidateService:
    - location: Scripts/validate.sh
      timeout: 60
      runas: root