version: 0.0
os: linux
hooks:
  AfterInstall:
    - location: Scripts/compile.sh
      timeout: 60
      runas: root
  ApplicationStart:
    - location: Scripts/start.sh
      timeout: 180
      runas: root
  ValidateService:
    - location: Scripts/validate.sh
      timeout: 60
      runas: root